version: "2"
services:
  guacamole:
    image: andromeda9096/guacamole:v1
    container_name: guacamole
    volumes:
      - postgres:/config
    ports:
      - 8080:8080
volumes:
  postgres:
    driver: local
